name = "detect-app-backend"

[phases.setup]
nixPkgs = ["libGL", "glib"]

[phases.install]
cmds = [
    "pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt",
]

[start]
cmd = "PYTHONPATH=. uvicorn app.main:app --host 0.0.0.0 --port 8000"
